import type { Metadata } from "next";
import { Inter, Open_Sans, Poppins } from "next/font/google";
import "@/styles/globals.css";
import Providers from "@/providers/QueryProvider";
import VideoModal from "@/components/common/VideoModal";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "TMovies",
  description: "Generated by MTIT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} ${open_sans.variable} antialiased`}
      >
        <Providers>
          <Header />
          {children}
          <VideoModal />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
